# Generated by Django 3.2.9 on 2021-11-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211117_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.order'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.usertype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cart'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.address'),
        ),
    ]
