# Generated by Django 3.2.9 on 2021-11-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211117_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
