# Generated by Django 3.2.9 on 2021-11-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_type_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.Product', verbose_name='products'),
        ),
    ]
