# Generated by Django 3.2.9 on 2021-11-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Usúario', 'verbose_name_plural': 'Usúarios'},
        ),
    ]
