# Generated by Django 3.2.9 on 2021-11-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
