# Generated by Django 3.2.9 on 2021-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211114_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
